name: CI

on: [push, pull_request]

jobs:
  build:
    name: Generate build and check code formatting

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Use Node 24
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm ci
      - run: npm run format:check
      - run: npm run build
